#!/bin/bash
# Diagnose why unpackerr isn't extracting completed downloads
# (arrs showing "might need to be extracted" warnings in their queues).
#
# Run on the NAS:
#   bash /volume1/docker/media/diagnose-unpackerr.sh
# Or scp + run:
#   scp diagnose-unpackerr.sh user@nas:/tmp/
#   ssh user@nas "bash /tmp/diagnose-unpackerr.sh"

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Find the install dir — try common spots.
for candidate in \
    "$SCRIPT_DIR" \
    "$SCRIPT_DIR/scripts/.." \
    /volume1/docker/media \
    /volume1/docker/media/scripts/.. ; do
    if [ -f "$candidate/.env" ] || [ -f "$candidate/scripts/.env" ]; then
        INSTALL_DIR="$(cd "$candidate" && pwd)"
        break
    fi
done
INSTALL_DIR="${INSTALL_DIR:-/volume1/docker/media}"

if [ -f "$INSTALL_DIR/scripts/.env" ]; then
    ENV_FILE="$INSTALL_DIR/scripts/.env"
elif [ -f "$INSTALL_DIR/.env" ]; then
    ENV_FILE="$INSTALL_DIR/.env"
else
    echo "Couldn't find .env under $INSTALL_DIR — set INSTALL_DIR env var and re-run."
    exit 1
fi

env_val() { grep -m1 "^$1=" "$ENV_FILE" 2>/dev/null | cut -d'=' -f2- | tr -d '\r'; }

DATA_ROOT="$(env_val DATA_ROOT)"
SONARR_KEY="$(env_val SONARR_API_KEY)"
RADARR_KEY="$(env_val RADARR_API_KEY)"
LIDARR_KEY="$(env_val LIDARR_API_KEY)"
ENABLE_UNPACKERR="$(env_val ENABLE_UNPACKERR)"
ENABLE_SONARR="$(env_val ENABLE_SONARR)"
ENABLE_RADARR="$(env_val ENABLE_RADARR)"
ENABLE_LIDARR="$(env_val ENABLE_LIDARR)"

# Default-on opt-out semantics: missing/blank/"true"/"1"/"yes"/"on" = enabled.
# Mirrors is_enabled() in scripts/setup.sh + is_enabled() in setup-arr-config.py.
is_on() {
    local v="${1:-true}"
    case "${v,,}" in
        ''|true|1|yes|on) return 0 ;;
        *) return 1 ;;
    esac
}

# Use loopback for arr API calls (avoids LAN-firewall issues during diag).
# Published host ports per docker-compose.yml.
ARR_HOST="127.0.0.1"
SONARR="http://$ARR_HOST:49152"
RADARR="http://$ARR_HOST:49151"
LIDARR="http://$ARR_HOST:49154"
CONF="$INSTALL_DIR/unpackerr/config/unpackerr.conf"

section() { echo ""; echo "── $1 ─────────────────────────────────────────────"; }
indent()  { sed 's/^/    /'; }

# ── Environment ───────────────────────────────────────────────────────────────

section "Environment"
echo "  INSTALL_DIR=$INSTALL_DIR"
echo "  ENV_FILE=$ENV_FILE"
echo "  DATA_ROOT=$DATA_ROOT"
echo "  ENABLE_UNPACKERR=${ENABLE_UNPACKERR:-<unset, default ON>} → $(is_on "$ENABLE_UNPACKERR" && echo enabled || echo DISABLED)"
echo "  ENABLE_SONARR=${ENABLE_SONARR:-<unset>}   SONARR_API_KEY=$([ -n "$SONARR_KEY" ] && echo "present (...${SONARR_KEY: -4})" || echo MISSING)"
echo "  ENABLE_RADARR=${ENABLE_RADARR:-<unset>}   RADARR_API_KEY=$([ -n "$RADARR_KEY" ] && echo "present (...${RADARR_KEY: -4})" || echo MISSING)"
echo "  ENABLE_LIDARR=${ENABLE_LIDARR:-<unset>}   LIDARR_API_KEY=$([ -n "$LIDARR_KEY" ] && echo "present (...${LIDARR_KEY: -4})" || echo MISSING)"

# ── Container ─────────────────────────────────────────────────────────────────

section "Container"
STATUS="$(docker inspect -f '{{.State.Status}}' unpackerr 2>/dev/null || true)"
if [ -z "$STATUS" ]; then
    echo "  unpackerr container DOES NOT EXIST."
    echo ""
    echo "  Most likely: ENABLE_UNPACKERR is false in .env (or was, last time setup.sh"
    echo "  ran — see scripts/setup.sh's prune_stopped_optouts, which removes containers"
    echo "  for opted-out services). Fix:"
    echo "    1) set ENABLE_UNPACKERR=true in $ENV_FILE"
    echo "    2) delete the stock conf BEFORE bringing up the container, otherwise"
    echo "       setup-arr-config.py's write_config_file skips it (see Config section):"
    echo "         rm -f '$CONF'"
    echo "    3) cd $INSTALL_DIR/scripts && bash setup.sh"
    echo "       (or:  COMPOSE_PROFILES=unpackerr docker compose up -d unpackerr )"
else
    EXIT_CODE="$(docker inspect -f '{{.State.ExitCode}}' unpackerr 2>/dev/null)"
    RESTARTS="$(docker inspect -f '{{.RestartCount}}' unpackerr 2>/dev/null)"
    STARTED="$(docker inspect -f '{{.State.StartedAt}}' unpackerr 2>/dev/null | cut -d. -f1)"
    echo "  status=$STATUS  exit_code=$EXIT_CODE  restarts=$RESTARTS  started=$STARTED"
    if [ "$STATUS" != "running" ]; then
        echo "  → not running. See 'Recent logs' below for the exit reason."
    fi
fi

# ── Config file ───────────────────────────────────────────────────────────────

section "Config file"
if [ ! -f "$CONF" ]; then
    echo "  $CONF NOT FOUND."
    echo "  → setup-arr-config.py never wrote a conf. Re-run:"
    echo "      cd $INSTALL_DIR/scripts && python3 setup-arr-config.py"
else
    SIZE="$(wc -c < "$CONF")"
    LINES="$(wc -l < "$CONF")"
    MTIME="$(stat -c '%y' "$CONF" 2>/dev/null | cut -d. -f1)"
    echo "  path=$CONF"
    echo "  size=${SIZE}B  lines=$LINES  mtime=$MTIME"
    if grep -q "generated by setup-arr-config.py" "$CONF"; then
        echo "  source: ✓ our generated conf (setup-arr-config.py)"
    else
        echo "  source: ⚠  UPSTREAM STOCK TEMPLATE — our setup never wrote the real conf!"
        echo ""
        echo "  Why: the unpackerr image drops a stock unpackerr.conf into /config on"
        echo "  first run. setup-arr-config.py uses write_config_file (line ~2966), which"
        echo "  skips when the file already exists. If the container ever booted before"
        echo "  setup-arr-config.py got to it, we stay stuck on the stock template —"
        echo "  every arr block has api_key commented out, so unpackerr polls nothing."
        echo ""
        echo "  Fix:"
        echo "    rm '$CONF'"
        echo "    cd $INSTALL_DIR/scripts && python3 setup-arr-config.py"
        echo "    docker restart unpackerr 2>/dev/null || true"
    fi
    echo ""
    echo "  Active arr blocks (uncommented):"
    CONF_PATH="$CONF" python3 -c '
import os, re
content = open(os.environ["CONF_PATH"]).read()
blocks = re.split(r"\n(?=\[\[)", content)
seen_real = False
for blk in blocks:
    m = re.match(r"\[\[(\w+)\]\]", blk.strip())
    if not m:
        continue
    name = m.group(1)
    if name == "header":
        continue
    body = [l for l in blk.splitlines()[1:] if l.strip() and not l.strip().startswith("#")]
    if not body:
        print(f"    [[{name}]] — all commented out")
        continue
    api_key = url = paths = ""
    for ln in body:
        s = ln.strip()
        mk = re.match(r"api_key\s*=\s*\"([^\"]+)\"", s)
        if mk:
            api_key = mk.group(1)
        mu = re.match(r"url\s*=\s*\"([^\"]+)\"", s)
        if mu:
            url = mu.group(1)
        if re.match(r"paths\s*=", s):
            paths = s
    stub = (
        api_key in ("", "0123456789abcdef0123456789abcdef")
        or api_key.startswith("REPLACE_")
    )
    tag = "STUB" if stub else "real"
    if len(api_key) >= 8:
        short = api_key[:4] + "..." + api_key[-4:]
    else:
        short = api_key or "(none)"
    if not stub:
        seen_real = True
    print(f"    [[{name}]] url={url} api_key={short} [{tag}]")
    if paths:
        print(f"              {paths}")
if not seen_real:
    print("    !  No arr block has a real api_key — unpackerr will not poll anything.")
'
fi

# ── Container env (UN_* vars) ─────────────────────────────────────────────────

section "Container env (UN_* vars)"
if [ "${STATUS:-}" = "running" ]; then
    UN_VARS=$(docker exec unpackerr env 2>/dev/null | grep -E '^UN_' | sort)
    if [ -z "$UN_VARS" ]; then
        echo "  (no UN_* env vars set — expected; conf file is the only source of"
        echo "   truth as of the env-vars-removed change. If you see UN_* vars here,"
        echo "   the container was created against an older docker-compose.yml and"
        echo "   needs recreating:  docker compose up -d --force-recreate unpackerr )"
    else
        echo "$UN_VARS" | indent
        echo ""
        echo "  ⚠  UN_* env vars present means this container was created against an"
        echo "  older docker-compose.yml. Those env vars override the conf file and"
        echo "  cause empty-key '0 servers' bugs when .env is blank. Recreate with:"
        echo "    cd $INSTALL_DIR/scripts && docker compose up -d --force-recreate unpackerr"
    fi
else
    echo "  container not running — env unavailable"
fi

# ── Watched paths ─────────────────────────────────────────────────────────────

section "Watched paths"
# Compose mounts ${DATA_ROOT}:/data, so /data/X in the container == $DATA_ROOT/X
# on the NAS host. The conf template hardcodes these two roots (see
# setup-arr-config.py UNPACKERR_CONF + UNPACKERR_LIDARR_BLOCK).
for p in \
    "$DATA_ROOT/Downloads/Torrents/Completed" \
    "$DATA_ROOT/Downloads/Usenet/complete"; do
    if [ -d "$p" ]; then
        FILECOUNT=$(find "$p" -maxdepth 4 -type f 2>/dev/null | wc -l)
        ARCHIVES=$(find "$p" -maxdepth 4 -type f \
            \( -iname '*.rar' -o -iname '*.r0[0-9]' -o -iname '*.zip' \
               -o -iname '*.7z' -o -iname '*.tar' \) 2>/dev/null | wc -l)
        echo "  $p ✓  total_files=$FILECOUNT  archives=$ARCHIVES"
        if [ "$ARCHIVES" -gt 0 ]; then
            echo "    First 5 archives:"
            find "$p" -maxdepth 4 -type f \
                \( -iname '*.rar' -o -iname '*.zip' -o -iname '*.7z' \) 2>/dev/null \
                | head -5 | indent | indent
        fi
    else
        echo "  $p ✗ MISSING (unpackerr will silently never see this path)"
    fi
done

# ── Recent logs ───────────────────────────────────────────────────────────────

section "Recent logs"
if [ -n "${STATUS:-}" ]; then
    echo "  Last 30 lines:"
    docker logs --tail 30 unpackerr 2>&1 | indent
    echo ""
    echo "  Error/warn from last 500:"
    docker logs --tail 500 unpackerr 2>&1 \
        | grep -iE 'error|warn|fail|401|403|404|refused|timeout|no such' \
        | tail -20 | indent
else
    echo "  container missing — no logs"
fi

# ── Arr queue ─────────────────────────────────────────────────────────────────

section "Arr queue — items mentioning extract / rar / archive"
# The arrs flag completed downloads that contain archives with messages
# like "may need to be extracted" or "X.rar". These are exactly what
# unpackerr is supposed to process; if items pile up here, unpackerr is
# either off, mis-pointed, or unauthenticated.
queue_dump() {
    local name="$1" url="$2" key="$3" enabled="$4" apiver="$5"
    if ! is_on "$enabled"; then echo "  [$name] disabled in .env — skipping"; return; fi
    if [ -z "$key" ]; then echo "  [$name] no API key in .env — skipping"; return; fi
    local resp
    resp="$(curl -s -m 10 -H "X-Api-Key: $key" \
        "$url/api/$apiver/queue?pageSize=200&includeUnknownSeriesItems=true" 2>/dev/null)"
    if [ -z "$resp" ]; then echo "  [$name] no API response — service down or wrong port"; return; fi
    echo "  [$name]"
    RESP="$resp" python3 -c '
import os, json
try:
    d = json.loads(os.environ["RESP"])
except Exception as e:
    print(f"    parse error: {e}")
    raise SystemExit
records = d.get("records", [])
print(f"    queue size: {len(records)}")
stuck = []
for r in records:
    msgs = []
    for sm in r.get("statusMessages", []) or []:
        for m in sm.get("messages", []) or []:
            msgs.append(m)
    title = (r.get("title") or "(no title)")[:80]
    flat = " | ".join(msgs).lower()
    if any(k in flat for k in ("extract", "rar", "archive", "unpack")):
        stuck.append((title, "; ".join(msgs)))
print(f"    extract-related: {len(stuck)}")
for t, m in stuck[:10]:
    print(f"      - {t}")
    print(f"          -> {m}")
'
}
queue_dump sonarr "$SONARR" "$SONARR_KEY" "$ENABLE_SONARR" v3
queue_dump radarr "$RADARR" "$RADARR_KEY" "$ENABLE_RADARR" v3
queue_dump lidarr "$LIDARR" "$LIDARR_KEY" "$ENABLE_LIDARR" v1

# ── Summary ───────────────────────────────────────────────────────────────────

section "Summary — what to look for"
echo "  1. Container DOES NOT EXIST → unpackerr was opted-out. Re-enable in .env,"
echo "     delete the stock conf first (issue #2), then re-run setup.sh."
echo "  2. Config 'UPSTREAM STOCK TEMPLATE' → delete conf + re-run setup-arr-config.py."
echo "     This is the silent killer: container runs, but config polls nothing."
echo "  3. Any active block 'STUB' or 'all commented out' → unpackerr won't poll that arr."
echo "  4. [[lidarr]] block missing entirely → LIDARR_API_KEY was empty at setup time."
echo "     Fix: claim Lidarr (set admin pw to populate api key), re-run setup-arr-config.py."
echo "  5. Watched-path archives=0 but queue extract-related>0 → path mismatch:"
echo "     downloads are landing somewhere unpackerr isn't watching. Compare the conf"
echo "     paths above against qBit's save_path + SAB's complete-dir setting."
echo "  6. 401/403/auth in logs → conf has stale API keys; re-run setup-arr-config.py."
echo ""
