#!/bin/sh
# Mediarr — playlistsync orchestrator + scheduler.
#
# Two modes:
#   sync.sh            (default / container CMD) — SCHEDULER. Validate config,
#                      generate sockseek.conf from env, install a crontab from
#                      PLAYLIST_SYNC_CRON, optionally run one pass now, then
#                      exec crond in the foreground.
#   sync.sh run        — ONE PASS. For every configured source: build a track
#                      wishlist, hand it to sockseek (Soulseek-first, yt-dlp
#                      fallback), normalise the resulting .m3u, then turn it
#                      into a Plex playlist. Each source is independent — one
#                      failing never aborts the others.
#
# Data flow per source:
#   SiriusXM slug  --poll-xmplaylist.py-->  CSV(Artist,Title)  --\
#   Spotify URL    ----------------------------------------------> sockseek
#                                                                      |
#                          /data/Music/Playlists/<label>/{tracks,.m3u} |
#                                                                      v
#                     normalise .m3u to absolute /media paths  --> plex-upload.py
#                     (plex-upload.py scans the folder into Plex, waits, uploads)
#
# Why per-source folders (not one shared library): each playlist must be
# COMPLETE and independently playable in Plex. A shared index could skip a track
# already pulled for another playlist and then omit it from this one's .m3u. We
# trade some disk duplication for guaranteed-correct, self-contained playlists.
#
# POSIX sh (BusyBox ash). No `set -e`: a single source's failure must not abort
# the run, so errors are handled per-source and tallied. Unset-var safety comes
# from disciplined ${VAR:-default} use rather than `set -u`.

CONF=/config/sockseek.conf
INDEX_DIR=/config/index
PLAYLISTS_ROOT=/data/Music/Playlists
CRON_ENV=/app/cron.env
CRONTAB=/etc/crontabs/root
SCRIPT_DIR="$(dirname "$0")"

log()  { printf '%s playlistsync: %s\n' "$(date '+%Y-%m-%dT%H:%M:%S%z')" "$*"; }
warn() { log "WARN: $*" >&2; }
die()  { log "ERROR: $*" >&2; exit 1; }

# Trim leading/trailing whitespace from $1 (echoes the result).
trim() { printf '%s' "$1" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//'; }

# Make a string safe to use as a single folder/file name: drop path separators
# and control chars, collapse to a clean label. Spaces are kept (Plex is fine
# with them). Echoes the sanitised label.
sanitize() {
    printf '%s' "$1" | sed 's#[/\\]#-#g; s/[[:cntrl:]]//g; s/^[[:space:]]*//; s/[[:space:]]*$//'
}

# Extract the playlist id from a Spotify URL for a deterministic fallback label.
spotify_id() {
    _id="${1##*/playlist/}"   # drop everything up to and incl. /playlist/
    _id="${_id%%\?*}"          # drop ?si=... query
    _id="${_id%%/*}"           # drop any trailing path
    printf '%s' "$_id"
}

# ── sockseek.conf generation ────────────────────────────────────────────────
# Creds + global prefs live in the conf (mode 600) rather than on the command
# line, so they never show up in `ps`. Per-source paths are passed as CLI flags.
write_conf() {
    mkdir -p "$(dirname "$CONF")" "$INDEX_DIR"
    umask 077
    {
        printf '# Generated by playlistsync sync.sh on each start — do not edit.\n'
        printf 'username = %s\n' "$(trim "${PLAYLIST_SLSK_USER}")"
        printf 'password = %s\n' "$(trim "${PLAYLIST_SLSK_PASS}")"
        printf 'pref-format = %s\n' "${PLAYLIST_PREF_FORMAT:-flac}"
        # Soulseek-first; yt-dlp is the fallback when a track has no acceptable
        # Soulseek source. ffmpeg (in the image) backs yt-dlp's extraction.
        printf 'yt-dlp = true\n'
        printf 'write-playlist = true\n'
        # Optional FREE Spotify Developer app credentials. When present, sockseek
        # reads Spotify playlists via the official API (robust); when absent it
        # falls back to the unauthenticated public path (works for public
        # playlists but is fragile — see the wiki).
        if [ -n "${SPOTIFY_CLIENT_ID:-}" ] && [ -n "${SPOTIFY_CLIENT_SECRET:-}" ]; then
            printf 'spotify-id = %s\n' "${SPOTIFY_CLIENT_ID}"
            printf 'spotify-secret = %s\n' "${SPOTIFY_CLIENT_SECRET}"
            # OAuth refresh token (from the wizard's "Connect Spotify") lets
            # sockseek read the user's PRIVATE playlists, not just public ones.
            if [ -n "${SPOTIFY_REFRESH_TOKEN:-}" ]; then
                printf 'spotify-refresh = %s\n' "${SPOTIFY_REFRESH_TOKEN}"
            fi
        fi
    } > "$CONF"
    log "wrote $CONF (pref-format=${PLAYLIST_PREF_FORMAT:-flac}, spotify-api=$( [ -n "${SPOTIFY_CLIENT_ID:-}" ] && echo yes || echo no ))"
}

# ── one source ──────────────────────────────────────────────────────────────
# Rewrite a .m3u so every track entry is an ABSOLUTE Plex-side path
# (/media/Music/Playlists/<label>/<file>). Plex's /playlists/upload matches each
# entry against indexed library items BY PATH; an absolute path equal to the
# file's indexed location matches exactly, instead of relying on Plex resolving a
# bare/relative entry against the .m3u's own directory (which not all Plex builds
# do). The downloader writes /data/Music/... paths; Plex sees the same tree at
# /media/Music, so we translate the prefix and re-root each basename there.
# #EXTINF/#EXTM3U/comment/blank lines are preserved verbatim.
normalise_m3u() {
    python3 - "$1" <<'PY'
import os, sys
p = sys.argv[1]
HOST_PREFIX = "/data/Music"
PLEX_PREFIX = "/media/Music"
# The playlist folder as Plex sees it, derived from the .m3u's own location.
host_dir = os.path.dirname(os.path.abspath(p))
plex_dir = (PLEX_PREFIX + host_dir[len(HOST_PREFIX):]
            if host_dir.startswith(HOST_PREFIX) else host_dir)
try:
    with open(p, encoding='utf-8', errors='replace') as f:
        lines = f.read().splitlines()
except OSError as e:
    sys.stderr.write("normalise_m3u: cannot read %s: %s\n" % (p, e))
    sys.exit(1)
out = []
for ln in lines:
    s = ln.rstrip()
    if s == '' or s.lstrip().startswith('#'):
        out.append(s)
    else:
        out.append(plex_dir + '/' + os.path.basename(s))
with open(p, 'w', encoding='utf-8') as f:
    f.write('\n'.join(out) + '\n')
PY
}

# True if the .m3u at $1 has at least one real (non-comment, non-blank) entry.
m3u_has_tracks() {
    [ -f "$1" ] && grep -qv '^[[:space:]]*\(#\|$\)' "$1" 2>/dev/null
}

# Download one source into its own playlist folder and push it to Plex.
#   $1 = label (Plex playlist title + folder + .m3u basename)
#   $2 = sockseek input-type (csv|spotify)
#   $3 = sockseek input (CSV path or Spotify URL)
process_source() {
    _label="$(sanitize "$1")"
    _type="$2"
    _input="$3"
    [ -n "$_label" ] || { warn "empty label for input '$_input' — skipping"; return 1; }
    # Once Soulseek has rejected the login this run, every source fails the same
    # way — skip the rest with one clear note instead of N stack traces.
    [ "${_SLSK_LOGIN_FAILED:-}" = "1" ] && { warn "[$_label] skipping — Soulseek login already failed this run (fix the credentials and re-run)"; return 1; }

    _dir="$PLAYLISTS_ROOT/$_label"
    _m3u="$_dir/$_label.m3u"
    _index="$INDEX_DIR/$_label.index"
    mkdir -p "$_dir"

    log "[$_label] downloading ($_type) ..."

    # name-format keeps the folder flat ("Artist - Title") so the playlist
    # folder maps cleanly to one Plex playlist. --index-path remembers prior
    # successes/failures so daily re-runs only fetch NEW additions.
    set -- \
        --config "$CONF" \
        --input-type "$_type" \
        --path "$_dir" \
        --name-format "{artist} - {title}" \
        --write-playlist \
        --playlist-path "$_m3u" \
        --index-path "$_index"
    if [ "$_type" = "csv" ]; then
        set -- "$@" --artist-col Artist --title-col Title
    fi

    # Stream sockseek's output live AND capture it, so a Soulseek LOGIN rejection
    # (INVALIDPASS) surfaces as a clear, actionable message instead of a raw .NET
    # stack trace + a generic "exited non-zero". The pipe's exit is tee's, so
    # capture sockseek's real exit via a marker file.
    _ss_out="/tmp/sockseek-out-$$"
    _ss_rc="/tmp/sockseek-rc-$$"
    { sockseek "$_input" "$@" 2>&1; echo $? > "$_ss_rc"; } | tee "$_ss_out"
    _rc="$(cat "$_ss_rc" 2>/dev/null || echo 1)"
    rm -f "$_ss_rc"
    if [ "$_rc" -ne 0 ]; then
        if grep -qiE 'INVALIDPASS|rejected login|Soulseek login failed|Login failed' "$_ss_out" 2>/dev/null; then
            warn "[$_label] Soulseek REJECTED the login — nothing downloads until this is fixed."
            warn "    The Playlist Sync Soulseek username/password is wrong, or the username is already taken on the Soulseek network (so the password can't match)."
            warn "    Fix: in the wizard's Playlist Sync section pick a UNIQUE username (NOT your main slskd account) + matching password, then re-run."
            _SLSK_LOGIN_FAILED=1
        else
            warn "[$_label] sockseek exited non-zero — continuing (partial results may still exist)"
        fi
    fi
    rm -f "$_ss_out"

    # The container runs as root, but the Music library is owned PUID:PGID. Match
    # it so Plex/Lidarr and the user can read/manage the new files (and so these
    # don't stand out as root-owned in an otherwise PUID-owned library).
    chown -R "${PUID:-1000}:${PGID:-1000}" "$_dir" 2>/dev/null || true

    if ! m3u_has_tracks "$_m3u"; then
        warn "[$_label] no tracks were downloaded (empty/missing .m3u) — skipping Plex upload"
        return 1
    fi

    normalise_m3u "$_m3u" || { warn "[$_label] could not normalise .m3u — skipping Plex upload"; return 1; }

    log "[$_label] uploading playlist to Plex ..."
    if python3 "$SCRIPT_DIR/plex-upload.py" "$_dir" "$_label"; then
        log "[$_label] done."
        return 0
    fi
    warn "[$_label] Plex upload failed (tracks are downloaded; will retry next run)"
    return 1
}

# ── one full pass ───────────────────────────────────────────────────────────
run_pass() {
    # Always regenerate the conf from the CURRENT env so a credential/source
    # change is picked up on a manual `sync.sh run` too (the scheduler already
    # regenerates on every start). Previously this only wrote when the conf was
    # absent, so `sync.sh run` after a cred edit silently reused the old conf.
    write_conf
    mkdir -p "$PLAYLISTS_ROOT" "$INDEX_DIR"

    _ok=0
    _fail=0
    _any=0
    _SLSK_LOGIN_FAILED=0

    # SiriusXM channels: each slug -> xmplaylist rotation CSV -> sockseek.
    if [ -n "${SIRIUSXM_CHANNELS:-}" ]; then
        _OLDIFS=$IFS; IFS=','
        for _slug in $SIRIUSXM_CHANNELS; do
            IFS=$_OLDIFS
            _slug="$(trim "$_slug")"
            [ -n "$_slug" ] || continue
            _any=1
            _csv="/tmp/sxm-$(sanitize "$_slug").csv"
            log "[SiriusXM - $_slug] polling xmplaylist ..."
            if python3 "$SCRIPT_DIR/poll-xmplaylist.py" "$_slug" "$_csv" \
                    ${PLAYLIST_SXM_DAYS:+--days "$PLAYLIST_SXM_DAYS"} \
                    ${PLAYLIST_SXM_MIN_PLAYS:+--min-plays "$PLAYLIST_SXM_MIN_PLAYS"}; then
                if process_source "SiriusXM - $_slug" csv "$_csv"; then
                    _ok=$((_ok+1)); else _fail=$((_fail+1)); fi
            else
                warn "[SiriusXM - $_slug] xmplaylist poll failed — skipping"
                _fail=$((_fail+1))
            fi
            rm -f "$_csv"
            IFS=','
        done
        IFS=$_OLDIFS
    fi

    # Spotify playlists: "Label|URL" (custom title) or bare "URL" (id-derived).
    # sockseek needs your OWN Spotify Developer app for ALL Spotify inputs —
    # even public playlists — so if the creds are missing, skip Spotify with a
    # clear note (SiriusXM still runs). The installer validates this too, but
    # guard here for hand-edited .env files.
    if [ -n "${SPOTIFY_PLAYLISTS:-}" ] && { [ -z "${SPOTIFY_CLIENT_ID:-}" ] || [ -z "${SPOTIFY_CLIENT_SECRET:-}" ]; }; then
        _any=1
        warn "SPOTIFY_PLAYLISTS is set but SPOTIFY_CLIENT_ID/SECRET are missing — sockseek requires your own free Spotify Developer app for every Spotify input (even public playlists). Skipping Spotify this run; SiriusXM is unaffected."
    elif [ -n "${SPOTIFY_PLAYLISTS:-}" ]; then
        _OLDIFS=$IFS; IFS=','
        for _entry in $SPOTIFY_PLAYLISTS; do
            IFS=$_OLDIFS
            _entry="$(trim "$_entry")"
            [ -n "$_entry" ] || continue
            _any=1
            case "$_entry" in
                *"|"*) _label="$(trim "${_entry%%|*}")"; _url="$(trim "${_entry#*|}")" ;;
                *)     _url="$_entry"; _label="Spotify - $(spotify_id "$_url")" ;;
            esac
            if process_source "$_label" spotify "$_url"; then
                _ok=$((_ok+1)); else _fail=$((_fail+1)); fi
            IFS=','
        done
        IFS=$_OLDIFS
    fi

    if [ "$_any" -eq 0 ]; then
        warn "no sources configured (SIRIUSXM_CHANNELS and SPOTIFY_PLAYLISTS both empty) — nothing to do"
        return 0
    fi
    log "pass complete: $_ok playlist(s) updated, $_fail failed."
    [ "$_fail" -eq 0 ]
}

# ── scheduler ───────────────────────────────────────────────────────────────
# die_slow: like die() but sleeps first so a misconfigured .env doesn't
# crash-loop fast. The container is `restart: on-failure:5` (see compose) —
# without this pause a validate() exit-1 burns all 5 restarts in seconds and
# hammers the daemon. Mirrors recyclarr-trigger's sleep-before-exit. Only used
# for the config-error path; the `unknown mode` die() stays fast (it's an
# operator typo, not a restart loop).
die_slow() { log "ERROR: $*" >&2; sleep 60; exit 1; }

validate() {
    [ -n "${PLAYLIST_SLSK_USER:-}" ] && [ -n "${PLAYLIST_SLSK_PASS:-}" ] \
        || die_slow "PLAYLIST_SLSK_USER / PLAYLIST_SLSK_PASS are required (a 2nd free Soulseek account — slskd holds the stack's one session). Set them in .env and re-run setup."
    [ -n "${SIRIUSXM_CHANNELS:-}" ] || [ -n "${SPOTIFY_PLAYLISTS:-}" ] \
        || die_slow "no sources configured: set SIRIUSXM_CHANNELS and/or SPOTIFY_PLAYLISTS in .env."
}

scheduler() {
    validate
    write_conf

    _cron="${PLAYLIST_SYNC_CRON:-0 4 * * *}"

    # BusyBox cron runs jobs with a bare env, so snapshot ours (creds included —
    # hence mode 600) for the job to source. export -p quotes values safely.
    ( umask 077; export -p > "$CRON_ENV" )

    mkdir -p "$(dirname "$CRONTAB")"
    # Job output is redirected to PID 1's stdout (tini) so it lands in
    # `docker logs`. The whole pipeline runs under one shell so the env sources
    # before sync.sh.
    printf '%s /bin/sh -c ". %s; %s run" >> /proc/1/fd/1 2>&1\n' \
        "$_cron" "$CRON_ENV" "$SCRIPT_DIR/sync.sh" > "$CRONTAB"
    chmod 600 "$CRONTAB"
    log "scheduled: '$_cron' (cron) — $(grep -c . "$CRONTAB") job(s)"

    # Optional immediate pass so enabling the feature shows results without
    # waiting for the first cron tick. Failure here is non-fatal: the scheduler
    # must still come up so the cron keeps trying.
    if [ "${PLAYLIST_RUN_ON_START:-true}" = "true" ]; then
        log "running an initial pass (PLAYLIST_RUN_ON_START=true) ..."
        run_pass || warn "initial pass had failures — the schedule will retry"
    fi

    log "handing off to crond (foreground)."
    exec crond -f -l 8 -L /dev/stdout
}

case "${1:-}" in
    run)        shift; run_pass ;;
    scheduler|"") scheduler ;;
    *)          die "unknown mode '$1' (use: no args = scheduler, or 'run' = one pass)" ;;
esac
