#!/usr/bin/env python3
"""
setup-dispatcharr.py — Seed Live TV (Dispatcharr) end to end

Runs as setup.sh step 10, EVERY install/update pass, and is idempotent:

  1. Exits 0 immediately unless ENABLE_DISPATCHARR is explicitly true
     (opt-in semantics — a missing key counts as OFF, mirroring
     is_optin_enabled in setup.sh / isOptInEnabled in env-render.ts).
  2. Waits out Dispatcharr's slow first boot (bundled PostgreSQL init +
     Django migrations — minutes on a NAS).
  3. Creates the admin account via the one-time unauthenticated
     POST /api/accounts/initialize-superuser/ (only possible while NO admin
     exists — afterwards Dispatcharr just reports superuser_exists=true, so
     this can never clobber an existing login).
  4. Signs in (JWT: POST /api/accounts/token/ → Bearer access token).
  5. Pre-seeds each channel pack in LIVETV_CHANNEL_PACKS: an M3U account
     (playlist URL, daily refresh) + a matching XMLTV EPG source. All FREE
     ad-supported (FAST) services — the providers' own public streams, ads
     intact; playlists community-maintained (BuddyChewChew/app-m3u-generator,
     rebuilt daily from i.mjh.nz data), guide XML from i.mjh.nz.
  6. After each account's first parse lands, flips every channel group to
     enabled + auto_channel_sync and re-triggers a refresh, so Dispatcharr
     auto-creates CHANNELS from the imported streams (streams alone don't
     appear in the tuner outputs — only channels do).
  7. MEDIA_SERVER=jellyfin + JELLYFIN_API_KEY set: registers Dispatcharr as
     an M3U tuner + XMLTV guide in Jellyfin (free live TV & DVR). Plex needs
     a manual one-time DVR setup (and Plex Pass) — printed at the end.

Failure posture (matches the indexer scripts' warn-not-fail principle):
only "the dispatcharr container never became reachable" is a hard failure
(exit 1) — that means the deploy itself is broken. Everything else warns and
exits 0; re-runs heal whatever was skipped.

Env (.env):
    ENABLE_DISPATCHARR       gate (explicit true/1/yes/on)
    LAN_IP                   NAS LAN IP (Dispatcharr at http://<LAN_IP>:9191)
    DISPATCHARR_ADMIN_USER   admin login the installer creates + uses
    DISPATCHARR_ADMIN_PASS
    LIVETV_CHANNEL_PACKS     comma list: pluto,samsungtvplus,plextv,roku,tubi
                             (empty = seed nothing; bring your own sources)
    MEDIA_SERVER             plex (default) | jellyfin
    JELLYFIN_API_KEY         enables the Jellyfin tuner/guide wiring
    LIVETV_SYNC_TIMEOUT      seconds to wait for playlist parses (default 300)
"""

import json
import os
import re
import sys
import time
from urllib.request import Request, urlopen
from urllib.error import HTTPError, URLError

# ── Terminal colours ──────────────────────────────────────────────────────────

GREEN  = "\033[32m"
RED    = "\033[31m"
YELLOW = "\033[33m"
BOLD   = "\033[1m"
RESET  = "\033[0m"

errors = 0

def ok(msg):   print(f"  {GREEN}✔{RESET}  {msg}")
def skip(msg): print(f"  –  {msg}")
def info(msg): print(f"  ℹ  {msg}")
def warn(msg): print(f"  {YELLOW}!{RESET}  {msg}")
def fail(msg):
    global errors; errors += 1
    print(f"  {RED}✘{RESET}  {msg}")
def section(title):
    print(f"\n{BOLD}━━━ {title} {'━' * max(0, 52 - len(title))}{RESET}")

# ── Channel packs ─────────────────────────────────────────────────────────────
#
# Ids mirror LIVETV_PACKS in installer/src/shared/env-render.ts (the wizard's
# checkbox list) and env-schema.ts's token validation — keep all three in
# lock-step. Playlists: BuddyChewChew/app-m3u-generator, rebuilt daily by
# GitHub Actions from i.mjh.nz channel data (i.mjh.nz itself stopped hosting
# playlists in favour of EPG-only). Guide XML: i.mjh.nz per-service feeds
# (updated daily), except Tubi whose EPG the generator self-hosts. URLs
# verified live 2026-07-13; channel counts are that day's, shown in the wizard
# as hints only.

_PLAYLISTS = "https://raw.githubusercontent.com/BuddyChewChew/app-m3u-generator/main/playlists"

PACKS = {
    "pluto": {
        "name": "Pluto TV",
        "m3u":  f"{_PLAYLISTS}/plutotv_us.m3u",
        "epg":  "https://i.mjh.nz/PlutoTV/us.xml.gz",
    },
    "samsungtvplus": {
        "name": "Samsung TV Plus",
        "m3u":  f"{_PLAYLISTS}/samsungtvplus_us.m3u",
        "epg":  "https://i.mjh.nz/SamsungTVPlus/us.xml.gz",
    },
    "plextv": {
        "name": "Plex Live TV",
        "m3u":  f"{_PLAYLISTS}/plex_us.m3u",
        "epg":  "https://i.mjh.nz/Plex/us.xml.gz",
    },
    "roku": {
        "name": "Roku Channel",
        "m3u":  f"{_PLAYLISTS}/roku_all.m3u",
        "epg":  "https://i.mjh.nz/Roku/epg.xml.gz",
    },
    "tubi": {
        "name": "Tubi",
        "m3u":  f"{_PLAYLISTS}/tubi_all.m3u",
        # Self-generated by the same repo (i.mjh.nz has no Tubi feed); this is
        # the exact url-tvg the generator writes into tubi_all.m3u's header.
        "epg":  f"{_PLAYLISTS}/tubi_epg.xml",
    },
}

# ── HTTP helpers ──────────────────────────────────────────────────────────────

TIMEOUT = 20

def api(base, path, method="GET", body=None, token=None, timeout=TIMEOUT):
    """Call the Dispatcharr API. Returns (status, parsed-json-or-None).
    Network-level failures return (0, None). Never raises."""
    headers = {"Accept": "application/json",
               "User-Agent": "setup-dispatcharr/1.0"}
    data = None
    if body is not None:
        data = json.dumps(body).encode("utf-8")
        headers["Content-Type"] = "application/json"
    if token:
        headers["Authorization"] = f"Bearer {token}"
    req = Request(f"{base}{path}", data=data, headers=headers, method=method)
    try:
        with urlopen(req, timeout=timeout) as resp:
            content = resp.read()
            try:
                return resp.status, (json.loads(content) if content else {})
            except ValueError:
                return resp.status, {}
    except HTTPError as e:
        detail = b""
        try:
            detail = e.read()[:300]
        except Exception:
            pass
        return e.code, {"_error": detail.decode(errors="replace")}
    except (URLError, OSError):
        return 0, None

def jf_api(base, path, key, method="GET", body=None):
    """Call the Jellyfin API (mirrors jellyfin-upload.py's header posture:
    send BOTH the legacy X-Emby-Token and the modern Authorization form).
    Returns (status, parsed-json-or-None); network failures (0, None)."""
    headers = {"Accept": "application/json",
               "X-Emby-Token": key,
               "Authorization": f'MediaBrowser Token="{key}"',
               "User-Agent": "setup-dispatcharr/1.0"}
    data = None
    if body is not None:
        data = json.dumps(body).encode("utf-8")
        headers["Content-Type"] = "application/json"
    req = Request(f"{base}{path}", data=data, headers=headers, method=method)
    try:
        with urlopen(req, timeout=TIMEOUT) as resp:
            content = resp.read()
            try:
                return resp.status, (json.loads(content) if content else {})
            except ValueError:
                return resp.status, {}
    except HTTPError as e:
        return e.code, None
    except (URLError, OSError):
        return 0, None

# ── .env reading (mirrors setup-bazarr-providers.py) ─────────────────────────

def _parse_env_value(s):
    s = s.strip()
    if s[:1] == '"':
        out = []
        i, n = 1, len(s)
        while i < n:
            c = s[i]
            if c == '\\' and i + 1 < n:
                d = s[i + 1]
                out.append('\n' if d == 'n' else '\r' if d == 'r' else d)
                i += 2
                continue
            if c == '"':
                break
            out.append(c)
            i += 1
        return ''.join(out)
    if s[:1] == "'":
        j = s.find("'", 1)
        return s[1:j] if j != -1 else s[1:]
    return re.split(r'\s#', s, 1)[0].strip()

def read_env(path):
    env = {}
    try:
        with open(path, encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#') or '=' not in line:
                    continue
                k, _, v = line.partition('=')
                v = _parse_env_value(v)
                if v:
                    env[k.strip()] = v
    except FileNotFoundError:
        pass
    return env

def read_env_merged(script_dir):
    # .env lives at the compose root. This script sits at INSTALL_DIR/scripts/
    # in the current layout (one parent up); include script_dir itself and two
    # parents for older layouts, same candidates as the indexer scripts.
    candidates = [
        script_dir,
        os.path.dirname(script_dir),
        os.path.dirname(os.path.dirname(script_dir)),
    ]
    env_dir = next((d for d in candidates if os.path.exists(os.path.join(d, '.env'))), script_dir)
    return read_env(os.path.join(env_dir, '.env'))

def is_optin(v):
    return (v or '').strip().lower() in ('true', '1', 'yes', 'on')

# ── Dispatcharr steps ─────────────────────────────────────────────────────────

def wait_ready(base, retries=60, interval=5):
    """Poll the unauthenticated initialize-superuser endpoint until Django
    serves JSON. First boot runs PostgreSQL init + migrations — minutes on a
    NAS — hence the generous window (default 60×5s = 5 min). Returns the last
    body ({'superuser_exists': bool}) or None if it never came up."""
    print(f"  Waiting for Dispatcharr at {base} (first boot runs database setup"
          " — this can take a few minutes) ...")
    for attempt in range(retries):
        status, body = api(base, "/api/accounts/initialize-superuser/")
        if status == 200 and isinstance(body, dict) and "superuser_exists" in body:
            return body
        time.sleep(interval)
    return None

def ensure_admin(base, user, password, superuser_exists):
    """Create the admin account if none exists yet. The endpoint is a no-op
    (reports superuser_exists=true) once ANY admin exists, so this can never
    overwrite a login the user made themselves."""
    if superuser_exists:
        skip("Admin account (already exists)")
        return
    status, body = api(base, "/api/accounts/initialize-superuser/",
                       method="POST",
                       body={"username": user, "password": password,
                             "email": "admin@mediarr.local"})
    if status == 200 and isinstance(body, dict) and body.get("superuser_exists"):
        ok(f"Created the Dispatcharr admin account ('{user}')")
    else:
        warn(f"Couldn't create the admin account (HTTP {status}) — trying to sign in anyway")

def get_token(base, user, password):
    """JWT sign-in. Returns the access token or None."""
    status, body = api(base, "/api/accounts/token/",
                       method="POST",
                       body={"username": user, "password": password})
    if status == 200 and isinstance(body, dict) and body.get("access"):
        return body["access"]
    return None

def _seeded_marker(install_dir, account_id):
    """Marker recording that WE already ran the channel-auto-sync pass for this
    account. Written after a successful group PATCH; its presence stops re-runs
    from re-enabling groups the user later disabled by hand in the Dispatcharr
    UI (the heal path must only fire for accounts we never finished seeding).
    Lives beside the data/ mount so relocation moves it with the service."""
    return os.path.join(install_dir, "dispatcharr", f".autosync-seeded-{account_id}")

def seed_pack(base, token, pack_id, pack, install_dir):
    """Create the pack's M3U account + EPG source if missing. Returns
    (sync_id, epg_created): sync_id is the M3U account id when it still needs
    the channel-auto-sync pass — a freshly CREATED account, or an existing one
    we never finished seeding (no marker; a prior run's timeout — the re-run
    heal path) — else None."""
    created_id = None
    epg_created = False

    # M3U account (name is the idempotency key).
    status, accounts = api(base, "/api/m3u/accounts/", token=token)
    if status != 200 or not isinstance(accounts, list):
        warn(f"{pack['name']}: couldn't list M3U accounts (HTTP {status}) — skipping")
        return None, False
    existing = next((a for a in accounts if a.get("name") == pack["name"]), None)
    if existing is not None:
        skip(f"{pack['name']} (M3U source already added)")
        # Heal path: a prior run may have timed out before enabling channel
        # auto-sync on this account's groups. Only when OUR seeding never
        # completed (no marker) — a user who deliberately disabled the groups
        # afterwards has the marker, and their choice stands.
        if (existing.get("id") is not None
                and not os.path.exists(_seeded_marker(install_dir, existing["id"]))
                and not any(g.get("auto_channel_sync")
                            for g in existing.get("channel_groups") or [])):
            created_id = existing["id"]
    else:
        status, body = api(base, "/api/m3u/accounts/", method="POST", token=token,
                           body={
                               "name": pack["name"],
                               "server_url": pack["m3u"],
                               "account_type": "STD",
                               "max_streams": 0,
                               "is_active": True,
                               # Hours between automatic playlist re-downloads.
                               # Daily matches the generator's own rebuild cadence.
                               "refresh_interval": 24,
                           })
        if status in (200, 201) and isinstance(body, dict) and body.get("id"):
            created_id = body["id"]
            ok(f"{pack['name']}: M3U source added")
            # Kick the first playlist download/parse explicitly — don't rely
            # on create-time side effects.
            api(base, f"/api/m3u/refresh/{created_id}/", method="POST", token=token)
        else:
            detail = (body or {}).get("_error", "") if isinstance(body, dict) else ""
            warn(f"{pack['name']}: M3U create failed (HTTP {status}) {detail[:120]}")

    # EPG source (own idempotency key).
    epg_name = f"{pack['name']} EPG"
    status, sources = api(base, "/api/epg/sources/", token=token)
    if status == 200 and isinstance(sources, list):
        if any(s.get("name") == epg_name for s in sources):
            skip(f"{epg_name} (already added)")
        else:
            status, body = api(base, "/api/epg/sources/", method="POST", token=token,
                               body={
                                   "name": epg_name,
                                   "source_type": "xmltv",
                                   "url": pack["epg"],
                                   "is_active": True,
                                   "refresh_interval": 24,
                               })
            if status in (200, 201):
                epg_created = True
                ok(f"{epg_name}: guide source added")
            else:
                detail = (body or {}).get("_error", "") if isinstance(body, dict) else ""
                warn(f"{epg_name}: create failed (HTTP {status}) {detail[:120]}")
    else:
        warn(f"{epg_name}: couldn't list EPG sources (HTTP {status}) — skipping")

    return created_id, epg_created

def enable_auto_sync(base, token, account_ids, timeout, install_dir):
    """For each M3U account that still needs seeding: wait for its first parse
    to land (its channel GROUPS only exist after parsing), then flip every
    group to enabled + auto_channel_sync and re-refresh — that second refresh
    is what fires Dispatcharr's sync_auto_channels task, which turns the
    imported streams into actual CHANNELS (only channels appear in the
    HDHR/M3U/EPG outputs the media server consumes). Round-robin with one
    shared deadline so five packs parse concurrently, not serially.

    Status machine (apps/m3u/tasks.py): a refresh ends at 'success' or
    'error'; 'idle' is only the never-refreshed default. An account that
    reads 'idle' but ALREADY HAS groups was parsed some time ago (heal path)
    — patch it straight away instead of waiting on a refresh that may not be
    running."""
    pending = dict(account_ids)  # id -> pack name (copy; we pop as we finish)
    deadline = time.time() + timeout
    while pending and time.time() < deadline:
        for aid in list(pending):
            status, acct = api(base, f"/api/m3u/accounts/{aid}/", token=token)
            if status != 200 or not isinstance(acct, dict):
                continue
            state = acct.get("status")
            has_groups = bool(acct.get("channel_groups"))
            if state in ("fetching", "parsing", "pending_setup") \
                    or (state == "idle" and not has_groups):
                continue
            name = pending.pop(aid)
            if state == "error":
                warn(f"{name}: playlist refresh reported an error "
                     f"({str(acct.get('last_message') or '')[:120]}) — "
                     "check M3U sources in the Dispatcharr UI")
                continue
            groups = acct.get("channel_groups") or []
            if not groups:
                warn(f"{name}: parsed but no channel groups found — "
                     "channels may need enabling in the Dispatcharr UI")
                continue
            payload = [{"channel_group": g.get("channel_group"),
                        "enabled": True,
                        "auto_channel_sync": True}
                       for g in groups if g.get("channel_group") is not None]
            status, body = api(base, f"/api/m3u/accounts/{aid}/", method="PATCH",
                               token=token, body={"channel_groups": payload})
            if status == 200:
                # Re-refresh so sync_auto_channels runs with the flags set —
                # it only fires after a successful account refresh.
                api(base, f"/api/m3u/refresh/{aid}/", method="POST", token=token)
                ok(f"{name}: auto-creating channels from {len(payload)} group(s)"
                   " (finishes in the background)")
                # Record that seeding completed, so re-runs never re-enable
                # groups the user later disables by hand (see _seeded_marker).
                try:
                    with open(_seeded_marker(install_dir, aid), "w",
                              encoding="utf-8") as f:
                        f.write("seeded\n")
                except OSError:
                    pass  # best-effort; worst case a re-run re-enables sync
            else:
                warn(f"{name}: couldn't enable channel auto-sync (HTTP {status}) — "
                     "enable it per group in the Dispatcharr UI (M3U → Groups)")
        if pending:
            time.sleep(5)
    for name in pending.values():
        warn(f"{name}: playlist still importing after {timeout}s — channels "
             "finish syncing in the background; re-run setup (or this script) "
             "later if they don't appear")

def wire_jellyfin(env, install_dir, lan_ip):
    """Register Dispatcharr as a Jellyfin M3U tuner + XMLTV guide. Best-effort
    and idempotent: tuner presence is checked via GET /LiveTv/TunerHosts; the
    guide POST has no reliable list endpoint across Jellyfin versions, so a
    marker file next to Dispatcharr's data prevents duplicate providers on
    re-runs."""
    jf_key = env.get("JELLYFIN_API_KEY", "").strip()
    if not jf_key:
        info("Jellyfin: no JELLYFIN_API_KEY yet — after Jellyfin's first-run "
             "setup, create one (Dashboard → API Keys), put it in .env and "
             "re-run setup; live TV then wires up automatically.")
        return
    jf = f"http://{lan_ip}:8096"
    tuner_url = f"http://{lan_ip}:9191/output/m3u"
    guide_url = f"http://{lan_ip}:9191/output/epg"

    status, tuners = jf_api(jf, "/LiveTv/TunerHosts", jf_key)
    if status == 0:
        warn("Jellyfin unreachable — skipping live-TV wiring (re-run setup later)")
        return
    if isinstance(tuners, list) and any((t or {}).get("Url") == tuner_url for t in tuners):
        skip("Jellyfin tuner (already registered)")
    else:
        status, _ = jf_api(jf, "/LiveTv/TunerHosts", jf_key, method="POST",
                           body={"Type": "m3u", "Url": tuner_url,
                                 "AllowHWTranscoding": True,
                                 "EnableStreamLooping": False,
                                 "ImportFavoritesOnly": False})
        if status in (200, 201, 204):
            ok("Jellyfin: Dispatcharr registered as a live-TV tuner")
        else:
            warn(f"Jellyfin tuner registration failed (HTTP {status}) — add it "
                 f"manually: Dashboard → Live TV → Tuner (M3U): {tuner_url}")
            return

    marker = os.path.join(install_dir, "dispatcharr", ".jellyfin-guide-wired")
    if os.path.exists(marker):
        skip("Jellyfin guide source (already registered)")
        return
    status, _ = jf_api(jf, "/LiveTv/ListingProviders", jf_key, method="POST",
                       body={"Type": "xmltv", "Path": guide_url})
    if status in (200, 201, 204):
        ok("Jellyfin: programme guide (XMLTV) registered")
        try:
            with open(marker, "w", encoding="utf-8") as f:
                f.write(guide_url + "\n")
        except OSError:
            pass  # marker is best-effort; worst case a re-run duplicates the guide entry
    else:
        warn(f"Jellyfin guide registration failed (HTTP {status}) — add it "
             f"manually: Dashboard → Live TV → Guide Data Providers (XMLTV): {guide_url}")

# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    script_dir = os.path.dirname(os.path.realpath(__file__))
    env        = read_env_merged(script_dir)

    if not is_optin(env.get('ENABLE_DISPATCHARR')):
        print("ℹ Live TV not enabled (ENABLE_DISPATCHARR is not true) — skipping.")
        sys.exit(0)

    lan_ip = env.get('LAN_IP', '')
    if not lan_ip:
        print("Error: LAN_IP not set in .env"); sys.exit(1)

    if env.get('INSTALL_DIR'):
        install_dir = env.get('INSTALL_DIR')
    elif os.path.basename(script_dir) == 'scripts':
        install_dir = os.path.dirname(script_dir)
    else:
        install_dir = script_dir

    admin_user = env.get('DISPATCHARR_ADMIN_USER', '').strip()
    admin_pass = env.get('DISPATCHARR_ADMIN_PASS', '')
    base = f"http://{lan_ip}:9191"

    print(f"\n{BOLD}╔══════════════════════════════════════════╗")
    print("║       Live TV Setup (Dispatcharr)        ║")
    print(f"╚══════════════════════════════════════════╝{RESET}")

    boot = wait_ready(base)
    if boot is None:
        # The container is deployed (this step only runs when opted in) but
        # never served HTTP — that's a real deploy failure, the one hard-fail.
        fail(f"Dispatcharr never became reachable at {base} — check "
             "'docker logs dispatcharr', then re-run setup.")
        sys.exit(1)

    section("Admin Account")
    if not admin_user or not admin_pass:
        warn("DISPATCHARR_ADMIN_USER / DISPATCHARR_ADMIN_PASS missing from .env — "
             "can't configure Dispatcharr. Set them (the wizard fills them in) "
             "and re-run setup; the container itself is up.")
        sys.exit(0)
    ensure_admin(base, admin_user, admin_pass, bool(boot.get("superuser_exists")))

    token = get_token(base, admin_user, admin_pass)
    if not token:
        warn("Couldn't sign in to Dispatcharr with the .env admin credentials. "
             "If you changed the password in the Dispatcharr UI, update "
             "DISPATCHARR_ADMIN_PASS in .env and re-run setup — skipping the "
             "channel seeding for now (the service itself is up).")
        sys.exit(0)

    # ── Channel packs ─────────────────────────────────────────────────────────

    section("Free Channel Packs")
    pack_ids = [t.strip().lower() for t in
                (env.get('LIVETV_CHANNEL_PACKS', '') or '').split(',') if t.strip()]
    unknown = [t for t in pack_ids if t not in PACKS]
    for t in unknown:
        warn(f"Unknown channel pack '{t}' in LIVETV_CHANNEL_PACKS — "
             f"valid: {', '.join(PACKS)}")
    pack_ids = [t for t in pack_ids if t in PACKS]

    if not pack_ids:
        info("No channel packs selected — add your own M3U/Xtream sources in "
             f"the Dispatcharr UI at {base}")
    else:
        created = {}
        any_epg_created = False
        for pid in pack_ids:
            aid, epg_created = seed_pack(base, token, pid, PACKS[pid], install_dir)
            any_epg_created = any_epg_created or epg_created
            if aid is not None:
                created[aid] = PACKS[pid]["name"]
        if any_epg_created:
            # Nudge the EPG importer once for the new sources (each source also
            # refreshes on its own schedule; this just makes the guide appear
            # on install day). Best-effort.
            api(base, "/api/epg/import/", method="POST", token=token)
        if created:
            section("Channel Auto-Sync")
            try:
                sync_timeout = int(env.get('LIVETV_SYNC_TIMEOUT', '300') or '300')
            except ValueError:
                sync_timeout = 300
            enable_auto_sync(base, token, created, sync_timeout, install_dir)

    # ── Media-server wiring ───────────────────────────────────────────────────

    section("Media Server")
    if (env.get('MEDIA_SERVER', 'plex') or 'plex').strip().lower() == 'jellyfin':
        wire_jellyfin(env, install_dir, lan_ip)
    else:
        info("Plex: live tuning inside Plex needs Plex Pass — add Dispatcharr "
             f"under Settings → Live TV & DVR → Set Up (HDHomeRun at {base}/hdhr, "
             f"XMLTV guide at {base}/output/epg).")
        info("No Plex Pass? Watch live TV in Dispatcharr's own web UI "
             f"({base}) — its DVR records into Media/Recordings either way, "
             "and Plex indexes those recordings like any other files.")

    # ── Summary ───────────────────────────────────────────────────────────────

    print(f"\n{'═' * 52}")
    if errors == 0:
        print(f"{GREEN}{BOLD}  Live TV setup done — no errors.{RESET}")
    else:
        print(f"{RED}{BOLD}  Done with {errors} error(s) — review output above.{RESET}")
    print(f"""
  Live TV:
  • Web UI + guide     {base}  (sign in: {admin_user})
  • Record shows       Dispatcharr → TV Guide → pick a show → Record
  • Recordings land in Data/Media/Recordings (your media server indexes them)
  • Add your own IPTV  Dispatcharr → M3U / EPG  (sources, Xtream Codes, …)
{'═' * 52}
""")
    sys.exit(0 if errors == 0 else 1)


if __name__ == '__main__':
    main()
