// Render the user-facing form values into a .env file. Mirrors the
// keys in nas/.env.example exactly. Anything not collected by the
// wizard is either omitted (auto-discovered later by setup-arr-config.py)
// or emitted with a documented default.

export interface EnvFormValues {
  // ── Identity
  PUID: string
  PGID: string
  TZ: string
  LAN_IP: string

  // ── Plex
  PLEX_CLAIM?: string

  // ── ARR Web UI auth (applied by setup-arr-config.py)
  ARR_USERNAME?: string
  ARR_PASSWORD?: string

  // ── qBittorrent
  QBITTORRENT_USER: string
  QBITTORRENT_PASS: string

  // ── SABnzbd usenet provider (optional — added on first install)
  USENET_HOST?: string
  USENET_PORT?: string
  USENET_USER?: string
  USENET_PASS?: string
  USENET_CONNECTIONS?: string
  USENET_SSL?: string         // '1' or '0'
  USENET_NAME?: string

  // ── VPN
  /** When 'false', setup.sh applies docker-compose.no-vpn.yml and gluetun
   *  is skipped. qBittorrent then runs on the regular bridge network. */
  VPN_ENABLED?: string          // 'true' | 'false' — default 'true'
  VPN_PROVIDER: string          // 'nordvpn' | 'protonvpn' | 'mullvad' | 'airvpn' | 'surfshark' | 'custom'
  VPN_TYPE: string              // 'wireguard' | 'openvpn'
  VPN_COUNTRIES: string         // 'United States,Canada'
  /** NordVPN-only: API token used to fetch a WireGuard private key. */
  NORDVPN_ACCESS_TOKEN?: string
  /** Generic WireGuard credentials (Gluetun reads these directly). */
  WIREGUARD_PRIVATE_KEY?: string
  WIREGUARD_ADDRESSES?: string      // tunnel address e.g. "10.2.0.2/32" — Proton, Mullvad, AirVPN
  WIREGUARD_PRESHARED_KEY?: string  // AirVPN
  /** OpenVPN credentials (Surfshark, etc.). */
  OPENVPN_USER?: string
  OPENVPN_PASSWORD?: string
  /** Free-form env block for the "Custom" provider escape hatch. */
  CUSTOM_VPN_ENV?: string
  /** Legacy field, kept for migration. New profiles use WIREGUARD_PRIVATE_KEY. */
  NORDVPN_PRIVATE_KEY?: string

  // ── Usenet indexers (paste API key to enable)
  ANIMETOSHO_API_KEY?: string
  NZBGEEK_API_KEY?: string
  NZBFINDER_API_KEY?: string
  DRUNKENSLUG_API_KEY?: string
  NZBPLANET_API_KEY?: string
  NZBCAT_API_KEY?: string
  DOGNZB_API_KEY?: string
  NINJACZENTRAL_API_KEY?: string
  TABULARASA_API_KEY?: string

  // ── Private torrent trackers
  AVISTAZ_USER?: string
  AVISTAZ_PASS?: string
  HHD_API_KEY?: string
  ANIMEBYTES_USER?: string
  ANIMEBYTES_PASS?: string
  ANIMETORRENTS_USER?: string
  ANIMETORRENTS_PASS?: string

  // ── Bazarr subtitle providers
  OPENSUBTITLES_USER?: string
  OPENSUBTITLES_PASS?: string
  OPENSUBTITLESCOM_USER?: string
  OPENSUBTITLESCOM_PASS?: string
  ADDIC7ED_USER?: string
  ADDIC7ED_PASS?: string
}

const ESCAPE = (v: string) => {
  // .env consumed by docker compose: quote if value contains whitespace
  // or special chars; escape embedded backslashes, double quotes,
  // dollar signs, and backticks (the last two trigger expansion inside
  // double quotes).
  if (v === '') return ''
  if (/[\s"$`\\]/.test(v)) {
    return `"${v.replace(/([\\"$`])/g, '\\$1')}"`
  }
  return v
}

const line = (k: string, v?: string) =>
  v === undefined || v === '' ? `${k}=` : `${k}=${ESCAPE(v)}`

export function renderEnv(v: EnvFormValues): string {
  return [
    '# Generated by Mediarr Installer',
    '# Identity',
    line('PUID', v.PUID),
    line('PGID', v.PGID),
    line('TZ', v.TZ),
    '',
    '# Network',
    line('LAN_IP', v.LAN_IP),
    '',
    '# Plex',
    line('PLEX_CLAIM', v.PLEX_CLAIM),
    '',
    '# ARR Web UI Auth',
    line('ARR_USERNAME', v.ARR_USERNAME),
    line('ARR_PASSWORD', v.ARR_PASSWORD),
    '',
    '# ARR API keys (auto-discovered after first boot — leave blank)',
    'SONARR_API_KEY=',
    'RADARR_API_KEY=',
    'LIDARR_API_KEY=',
    'PROWLARR_API_KEY=',
    'SABNZBD_API_KEY=',
    'BAZARR_API_KEY=',
    'SEERR_API_KEY=',
    '',
    '# qBittorrent WebUI',
    line('QBITTORRENT_USER', v.QBITTORRENT_USER),
    line('QBITTORRENT_PASS', v.QBITTORRENT_PASS),
    '',
    '# SABnzbd usenet provider (optional)',
    line('USENET_HOST', v.USENET_HOST),
    line('USENET_PORT', v.USENET_PORT || '563'),
    line('USENET_USER', v.USENET_USER),
    line('USENET_PASS', v.USENET_PASS),
    line('USENET_CONNECTIONS', v.USENET_CONNECTIONS || '8'),
    line('USENET_SSL', v.USENET_SSL || '1'),
    line('USENET_NAME', v.USENET_NAME || 'primary'),
    '',
    '# VPN — set VPN_ENABLED=true to route qBittorrent through gluetun.',
    '# Gluetun (the actual VPN client) reads VPN_SERVICE_PROVIDER + VPN_TYPE +',
    '# the per-provider credentials below. Unused vars are ignored.',
    line('VPN_ENABLED', v.VPN_ENABLED || 'false'),
    line('VPN_PROVIDER', v.VPN_PROVIDER),
    line('VPN_TYPE', v.VPN_TYPE),
    line('VPN_COUNTRIES', v.VPN_COUNTRIES),
    '# WireGuard credentials (Proton/Mullvad/AirVPN/NordVPN)',
    // NORDVPN_PRIVATE_KEY mirrors WIREGUARD_PRIVATE_KEY for back-compat;
    // old setup-nordvpn.sh and prior profiles still reference it.
    line('WIREGUARD_PRIVATE_KEY', v.WIREGUARD_PRIVATE_KEY || v.NORDVPN_PRIVATE_KEY),
    line('NORDVPN_PRIVATE_KEY', v.NORDVPN_PRIVATE_KEY || v.WIREGUARD_PRIVATE_KEY),
    line('NORDVPN_ACCESS_TOKEN', v.NORDVPN_ACCESS_TOKEN),
    line('WIREGUARD_ADDRESSES', v.WIREGUARD_ADDRESSES),
    line('WIREGUARD_PRESHARED_KEY', v.WIREGUARD_PRESHARED_KEY),
    '# OpenVPN credentials (Surfshark, others)',
    line('OPENVPN_USER', v.OPENVPN_USER),
    line('OPENVPN_PASSWORD', v.OPENVPN_PASSWORD),
    // Custom-provider escape hatch: paste raw env block. We expand it
    // here so docker-compose / gluetun sees the keys directly, and
    // skip lines that don't look like KEY=value.
    ...(v.CUSTOM_VPN_ENV
      ? ['# Custom VPN env (Custom provider escape hatch)',
         ...v.CUSTOM_VPN_ENV.split('\n')
            .map((l) => l.trim())
            .filter((l) => /^[A-Z_][A-Z0-9_]*=/.test(l))]
      : []),
    '',
    '# Usenet indexers',
    line('ANIMETOSHO_API_KEY', v.ANIMETOSHO_API_KEY),
    line('NZBGEEK_API_KEY', v.NZBGEEK_API_KEY),
    line('NZBFINDER_API_KEY', v.NZBFINDER_API_KEY),
    line('DRUNKENSLUG_API_KEY', v.DRUNKENSLUG_API_KEY),
    line('NZBPLANET_API_KEY', v.NZBPLANET_API_KEY),
    line('NZBCAT_API_KEY', v.NZBCAT_API_KEY),
    line('DOGNZB_API_KEY', v.DOGNZB_API_KEY),
    line('NINJACZENTRAL_API_KEY', v.NINJACZENTRAL_API_KEY),
    line('TABULARASA_API_KEY', v.TABULARASA_API_KEY),
    '',
    '# Private torrent trackers',
    line('AVISTAZ_USER', v.AVISTAZ_USER),
    line('AVISTAZ_PASS', v.AVISTAZ_PASS),
    line('HHD_API_KEY', v.HHD_API_KEY),
    line('ANIMEBYTES_USER', v.ANIMEBYTES_USER),
    line('ANIMEBYTES_PASS', v.ANIMEBYTES_PASS),
    line('ANIMETORRENTS_USER', v.ANIMETORRENTS_USER),
    line('ANIMETORRENTS_PASS', v.ANIMETORRENTS_PASS),
    '',
    '# Bazarr subtitle providers',
    line('OPENSUBTITLES_USER', v.OPENSUBTITLES_USER),
    line('OPENSUBTITLES_PASS', v.OPENSUBTITLES_PASS),
    line('OPENSUBTITLESCOM_USER', v.OPENSUBTITLESCOM_USER),
    line('OPENSUBTITLESCOM_PASS', v.OPENSUBTITLESCOM_PASS),
    line('ADDIC7ED_USER', v.ADDIC7ED_USER),
    line('ADDIC7ED_PASS', v.ADDIC7ED_PASS),
    '',
  ].join('\n')
}

// ── Indexer + provider catalogue (drives the toggle-card UI) ────────────────

export type IndexerCat = 'usenet-free' | 'usenet-paid' | 'tracker-private'

export interface IndexerDef {
  /** Form key */
  id: keyof EnvFormValues
  /** Display name */
  name: string
  /** Where to register / get an API key — opens externally */
  href?: string
  /** Brief one-liner */
  note?: string
  /** Auth fields the indexer needs */
  fields: { key: keyof EnvFormValues; label: string; password?: boolean }[]
  category: IndexerCat
}

export const USENET_INDEXERS: IndexerDef[] = [
  {
    id: 'NZBGEEK_API_KEY', name: 'NZBGeek',
    href: 'https://nzbgeek.info', note: 'Paid account.',
    fields: [{ key: 'NZBGEEK_API_KEY', label: 'API key' }],
    category: 'usenet-paid',
  },
  {
    id: 'NZBFINDER_API_KEY', name: 'NZBFinder',
    href: 'https://nzbfinder.ws', note: 'Paid account.',
    fields: [{ key: 'NZBFINDER_API_KEY', label: 'API key' }],
    category: 'usenet-paid',
  },
  {
    id: 'NZBPLANET_API_KEY', name: 'NZBPlanet',
    href: 'https://nzbplanet.net', note: 'Paid account.',
    fields: [{ key: 'NZBPLANET_API_KEY', label: 'API key' }],
    category: 'usenet-paid',
  },
  {
    id: 'NZBCAT_API_KEY', name: 'NZB.cat',
    href: 'https://nzb.cat', note: 'Paid account.',
    fields: [{ key: 'NZBCAT_API_KEY', label: 'API key' }],
    category: 'usenet-paid',
  },
  {
    id: 'DRUNKENSLUG_API_KEY', name: 'DrunkenSlug',
    href: 'https://drunkenslug.com', note: 'Invite-only.',
    fields: [{ key: 'DRUNKENSLUG_API_KEY', label: 'API key' }],
    category: 'usenet-paid',
  },
  {
    id: 'DOGNZB_API_KEY', name: 'DogNZB',
    href: 'https://dognzb.cr', note: 'Invite-only.',
    fields: [{ key: 'DOGNZB_API_KEY', label: 'API key' }],
    category: 'usenet-paid',
  },
  {
    id: 'NINJACZENTRAL_API_KEY', name: 'NinjaCentral',
    href: 'https://ninjacentral.co.za',
    fields: [{ key: 'NINJACZENTRAL_API_KEY', label: 'API key' }],
    category: 'usenet-paid',
  },
  {
    id: 'TABULARASA_API_KEY', name: 'Tabula Rasa',
    href: 'https://tabula-rasa.pw',
    fields: [{ key: 'TABULARASA_API_KEY', label: 'API key' }],
    category: 'usenet-paid',
  },
  {
    id: 'ANIMETOSHO_API_KEY', name: 'AnimeTosho (optional key)',
    href: 'https://animetosho.org', note: 'Free without a key; key only raises rate limits.',
    fields: [{ key: 'ANIMETOSHO_API_KEY', label: 'API key (optional)' }],
    category: 'usenet-free',
  },
]

export const PRIVATE_TRACKERS: IndexerDef[] = [
  {
    id: 'AVISTAZ_USER', name: 'AvistaZ', href: 'https://avistaz.to',
    note: 'Korean/Asian movies and TV.',
    fields: [
      { key: 'AVISTAZ_USER', label: 'Username' },
      { key: 'AVISTAZ_PASS', label: 'Password', password: true },
    ],
    category: 'tracker-private',
  },
  {
    id: 'HHD_API_KEY', name: 'HomieHelpDesk', href: 'https://homiehelpdesk.net',
    note: 'Korean movies/dramas.',
    fields: [{ key: 'HHD_API_KEY', label: 'API key' }],
    category: 'tracker-private',
  },
  {
    id: 'ANIMEBYTES_USER', name: 'AnimeBytes', href: 'https://animebytes.tv',
    note: 'Highest-quality anime tracker (invite-only).',
    fields: [
      { key: 'ANIMEBYTES_USER', label: 'Username' },
      { key: 'ANIMEBYTES_PASS', label: 'Password', password: true },
    ],
    category: 'tracker-private',
  },
  {
    id: 'ANIMETORRENTS_USER', name: 'AnimeTorrents', href: 'https://animetorrents.me',
    note: 'Anime (application-based).',
    fields: [
      { key: 'ANIMETORRENTS_USER', label: 'Username' },
      { key: 'ANIMETORRENTS_PASS', label: 'Password', password: true },
    ],
    category: 'tracker-private',
  },
]

export const BAZARR_PROVIDERS: IndexerDef[] = [
  {
    id: 'OPENSUBTITLES_USER', name: 'OpenSubtitles.org',
    href: 'https://www.opensubtitles.org', note: 'Free account.',
    fields: [
      { key: 'OPENSUBTITLES_USER', label: 'Username' },
      { key: 'OPENSUBTITLES_PASS', label: 'Password', password: true },
    ],
    category: 'usenet-free',
  },
  {
    id: 'OPENSUBTITLESCOM_USER', name: 'OpenSubtitles.com',
    href: 'https://www.opensubtitles.com', note: 'Free account; larger DB.',
    fields: [
      { key: 'OPENSUBTITLESCOM_USER', label: 'Username' },
      { key: 'OPENSUBTITLESCOM_PASS', label: 'Password', password: true },
    ],
    category: 'usenet-free',
  },
  {
    id: 'ADDIC7ED_USER', name: 'Addic7ed',
    href: 'https://www.addic7ed.com', note: 'Free account.',
    fields: [
      { key: 'ADDIC7ED_USER', label: 'Username' },
      { key: 'ADDIC7ED_PASS', label: 'Password', password: true },
    ],
    category: 'usenet-free',
  },
]
