// Render the user-facing form values into a .env file. Mirrors the
// keys in nas/.env.example. Anything not collected by the wizard is
// either omitted (auto-discovered later by setup-arr-config.py) or
// emitted with a documented default.

export interface EnvFormValues {
  // Identity
  PUID: string
  PGID: string
  TZ: string
  LAN_IP: string

  // VPN
  VPN_PROVIDER: string          // 'nordvpn'
  VPN_TYPE: string              // 'wireguard'
  VPN_COUNTRIES: string         // comma-separated, e.g. 'United States,Canada'
  NORDVPN_PRIVATE_KEY: string

  // qBittorrent WebUI
  QBITTORRENT_USER: string
  QBITTORRENT_PASS: string

  // Plex
  PLEX_CLAIM: string

  // Optional indexers (leave empty to skip)
  NZBGEEK_API_KEY?: string
  ANIMETOSHO_API_KEY?: string

  // Optional Bazarr providers
  OPENSUBTITLES_USERNAME?: string
  OPENSUBTITLES_PASSWORD?: string
  ADDIC7ED_USERNAME?: string
  ADDIC7ED_PASSWORD?: string
}

const ESCAPE = (v: string) => {
  // .env consumed by docker compose: quote if value contains whitespace
  // or special chars; escape embedded double quotes.
  if (v === '') return ''
  if (/[\s"$`\\]/.test(v)) {
    return `"${v.replace(/(["\\$`])/g, '\\$1')}"`
  }
  return v
}

const line = (k: string, v?: string) => (v === undefined || v === '' ? `${k}=` : `${k}=${ESCAPE(v)}`)

export function renderEnv(values: EnvFormValues): string {
  return [
    '# Generated by NAS Arr Installer',
    '# Identity',
    line('PUID', values.PUID),
    line('PGID', values.PGID),
    line('TZ', values.TZ),
    line('LAN_IP', values.LAN_IP),
    '',
    '# VPN',
    line('VPN_PROVIDER', values.VPN_PROVIDER),
    line('VPN_TYPE', values.VPN_TYPE),
    line('VPN_COUNTRIES', values.VPN_COUNTRIES),
    line('NORDVPN_PRIVATE_KEY', values.NORDVPN_PRIVATE_KEY),
    '',
    '# qBittorrent WebUI',
    line('QBITTORRENT_USER', values.QBITTORRENT_USER),
    line('QBITTORRENT_PASS', values.QBITTORRENT_PASS),
    '',
    '# Plex',
    line('PLEX_CLAIM', values.PLEX_CLAIM),
    '',
    '# Optional indexer credentials',
    line('NZBGEEK_API_KEY', values.NZBGEEK_API_KEY),
    line('ANIMETOSHO_API_KEY', values.ANIMETOSHO_API_KEY),
    '',
    '# Optional Bazarr providers',
    line('OPENSUBTITLES_USERNAME', values.OPENSUBTITLES_USERNAME),
    line('OPENSUBTITLES_PASSWORD', values.OPENSUBTITLES_PASSWORD),
    line('ADDIC7ED_USERNAME', values.ADDIC7ED_USERNAME),
    line('ADDIC7ED_PASSWORD', values.ADDIC7ED_PASSWORD),
    '',
  ].join('\n')
}
