// Auto-generated from https://xmplaylist.com/api/station — the free SiriusXM
// rotation directory Playlist Sync reads (no auth; send a User-Agent).
// ~171 channels; regenerate by re-fetching that endpoint. Populates the
// SiriusXM channel multi-select on the Configure screen; a custom-slug escape
// hatch in the UI covers any channel not in this snapshot.

export interface SiriusXmStation {
  /** xmplaylist deeplink slug — the value written to SIRIUSXM_CHANNELS. */
  slug: string
  /** Display name, e.g. "SiriusXM Hits 1". */
  name: string
  /** Dial number, e.g. "2". */
  number: string
}

export const SIRIUSXM_STATIONS: SiriusXmStation[] = [
  { slug: "siriusxmhits1", name: "SiriusXM Hits 1", number: "2" },
  { slug: "unwellmusic", name: "Unwell Music", number: "3" },
  { slug: "lifewithjohnmayer", name: "Life with John Mayer", number: "4" },
  { slug: "thepulse", name: "The Pulse", number: "5" },
  { slug: "poprocks", name: "PopRocks", number: "6" },
  { slug: "70son7", name: "70s on 7", number: "7" },
  { slug: "80son8", name: "80s on 8", number: "8" },
  { slug: "90son9", name: "90s on 9", number: "9" },
  { slug: "pop2k", name: "Pop2K", number: "10" },
  { slug: "the10sspot", name: "The 10s Spot", number: "11" },
  { slug: "kellyclarksonconnection", name: "The Kelly Clarkson Connection", number: "12" },
  { slug: "pitbullsglobalization", name: "Pitbull's Globalization", number: "13" },
  { slug: "thebridge", name: "The Bridge", number: "14" },
  { slug: "yachtrockradio", name: "Yacht Rock Radio", number: "15" },
  { slug: "theblend", name: "The Blend", number: "16" },
  { slug: "thecoffeehouse", name: "The Coffee House", number: "17" },
  { slug: "thebeatleschannel", name: "The Beatles Channel", number: "18" },
  { slug: "bobmarleystuffgong", name: "Bob Marley's Tuff Gong", number: "19" },
  { slug: "estreetradio", name: "E Street Radio", number: "20" },
  { slug: "undergroundgarage", name: "Underground Garage", number: "21" },
  { slug: "pearljamradio", name: "Pearl Jam Radio", number: "22" },
  { slug: "gratefuldead", name: "Grateful Dead", number: "23" },
  { slug: "radiomargaritaville", name: "Radio Margaritaville", number: "24" },
  { slug: "classicrewind", name: "Classic Rewind", number: "25" },
  { slug: "classicvinyl", name: "Classic Vinyl", number: "26" },
  { slug: "alt2k", name: "Alt2K", number: "27" },
  { slug: "thespectrum", name: "The Spectrum", number: "28" },
  { slug: "phishradio", name: "Phish Radio", number: "29" },
  { slug: "davematthewsbandradio", name: "Dave Matthews Band Radio", number: "30" },
  { slug: "tompettyradio", name: "Tom Petty Radio", number: "31" },
  { slug: "u2xradio", name: "U2 X-Radio", number: "32" },
  { slug: "1stwave", name: "1st Wave", number: "33" },
  { slug: "lithium", name: "Lithium", number: "34" },
  { slug: "siriusxmu", name: "SiriusXMU", number: "35" },
  { slug: "altnation", name: "Alt Nation", number: "36" },
  { slug: "octane", name: "Octane", number: "37" },
  { slug: "ozzysboneyard", name: "Ozzy's Boneyard", number: "38" },
  { slug: "hairnation", name: "Hair Nation", number: "39" },
  { slug: "liquidmetal", name: "Liquid Metal", number: "40" },
  { slug: "siriusxmturbo", name: "SiriusXM Turbo", number: "41" },
  { slug: "maximummetallica", name: "Maximum Metallica", number: "42" },
  { slug: "rockthebellsradio", name: "Rock The Bells Radio", number: "43" },
  { slug: "hiphopnation", name: "Hip-Hop Nation", number: "44" },
  { slug: "shade45", name: "Shade 45", number: "45" },
  { slug: "theheat", name: "The Heat", number: "46" },
  { slug: "heartsoul", name: "Heart & Soul", number: "47" },
  { slug: "theflow", name: "The Flow", number: "48" },
  { slug: "flex2k", name: "Flex2K", number: "49" },
  { slug: "siriusxmfly", name: "SiriusXM FLY", number: "50" },
  { slug: "thegroove", name: "The Groove", number: "51" },
  { slug: "bpm", name: "BPM", number: "52" },
  { slug: "diplosrevolution", name: "Diplo's Revolution", number: "53" },
  { slug: "studio54radio", name: "Studio 54 Radio", number: "54" },
  { slug: "siriusxmchill", name: "SiriusXM Chill", number: "55" },
  { slug: "thehighway", name: "The Highway", number: "56" },
  { slug: "y2kountry", name: "Y2Kountry", number: "57" },
  { slug: "primecountry", name: "Prime Country", number: "58" },
  { slug: "noshoesradio", name: "No Shoes Radio", number: "59" },
  { slug: "carriescountry", name: "Carrie's Country", number: "60" },
  { slug: "williesroadhouse", name: "Willie's Roadhouse", number: "61" },
  { slug: "outlawcountry", name: "Outlaw Country", number: "62" },
  { slug: "chrisstapletonradio", name: "Chris Stapleton Radio", number: "63" },
  { slug: "morganwallenradio", name: "Morgan Wallen Radio", number: "64" },
  { slug: "themessage", name: "The Message", number: "65" },
  { slug: "watercolors", name: "Watercolors", number: "66" },
  { slug: "realjazz", name: "Real Jazz", number: "67" },
  { slug: "kirkfranklinspraise", name: "Kirk Franklin's Praise", number: "68" },
  { slug: "onbroadway", name: "On Broadway", number: "69" },
  { slug: "siriuslysinatra", name: "Siriusly Sinatra", number: "70" },
  { slug: "40sjunction", name: "40s Junction", number: "71" },
  { slug: "50sgold", name: "50s Gold", number: "72" },
  { slug: "60sgold", name: "60s Gold", number: "73" },
  { slug: "smokeyssoultown", name: "Smokey's Soul Town", number: "74" },
  { slug: "bbkingsbluesville", name: "BB King's Bluesville", number: "75" },
  { slug: "elvisradio", name: "Elvis Radio", number: "76" },
  { slug: "bluegrassjunction", name: "Bluegrass Junction", number: "77" },
  { slug: "symphonyhall", name: "Symphony Hall", number: "78" },
  { slug: "messageworship", name: "Message Worship", number: "79" },
  { slug: "netflixisajokeradio", name: "Netflix Is A Joke Radio", number: "93" },
  { slug: "comedygreats", name: "Comedy Greats", number: "94" },
  { slug: "comedycentralradio", name: "Comedy Central Radio", number: "95" },
  { slug: "kevinhartslolradio", name: "Kevin Hart's LOL Radio", number: "96" },
  { slug: "comedyroundup", name: "Comedy Roundup", number: "97" },
  { slug: "purecomedy", name: "Pure Comedy", number: "98" },
  { slug: "sebastianmaniscalcocmdy", name: "Sebastian Maniscalco\u2019s Comedy Radio", number: "99" },
  { slug: "conanobrienradio", name: "Conan O'Brien Radio", number: "104" },
  { slug: "hotelcalifornia", name: "Hotel California", number: "105" },
  { slug: "disneyhits", name: "Disney Hits", number: "133" },
  { slug: "kidsplace", name: "Kids Place", number: "134" },
  { slug: "kidzbopradio", name: "KIDZ BOP Radio", number: "135" },
  { slug: "cocomelonfriends", name: "CoComelon & Friends", number: "136" },
  { slug: "holycultureradio", name: "Holy Culture Radio", number: "140" },
  { slug: "escape", name: "Escape", number: "149" },
  { slug: "billgaithersenlighten", name: "Bill Gaither's enLighten", number: "150" },
  { slug: "caliente", name: "Caliente", number: "152" },
  { slug: "aguila", name: "\u00c1guila", number: "153" },
  { slug: "envivo", name: "En Vivo", number: "154" },
  { slug: "latinvault", name: "Latin Vault", number: "155" },
  { slug: "attitudefranco", name: "Attitude Franco", number: "163" },
  { slug: "mixtapenorth", name: "Mixtape: North", number: "164" },
  { slug: "theindigiverse", name: "The Indigiverse", number: "165" },
  { slug: "racinesmusicales", name: "Racines Musicales", number: "166" },
  { slug: "siriusxmcomedyclub", name: "SiriusXM Comedy Club", number: "168" },
  { slug: "topofthecountryradio", name: "Top of the Country Radio", number: "171" },
  { slug: "theverge", name: "The Verge", number: "173" },
  { slug: "influencefranco", name: "Influence Franco", number: "174" },
  { slug: "siriusxm300", name: "SiriusXM 300", number: "300" },
  { slug: "roadtripradio", name: "Road Trip Radio", number: "301" },
  { slug: "andycohenskikilounge", name: "Andy Cohen's Kiki Lounge", number: "302" },
  { slug: "mosaic", name: "Mosaic", number: "305" },
  { slug: "deeptracks", name: "Deep Tracks", number: "308" },
  { slug: "jamon309", name: "Jam On 309", number: "309" },
  { slug: "bonjoviradio", name: "Bon Jovi Radio", number: "312" },
  { slug: "greendaysidiotnation", name: "Green Day's Idiot Nation", number: "314" },
  { slug: "redhotchilipeppers", name: "Red Hot Chili Peppers", number: "315" },
  { slug: "siriusxmsilk330", name: "SiriusXM Silk 330", number: "330" },
  { slug: "shaggyboombasticradio", name: "Shaggy Boombastic Radio", number: "332" },
  { slug: "radiomonaco", name: "Radio Monaco", number: "340" },
  { slug: "utopia", name: "Utopia", number: "341" },
  { slug: "bakersfieldbeat", name: "Bakersfield Beat", number: "349" },
  { slug: "redwhitebooze", name: "Red White & Booze", number: "350" },
  { slug: "northamericana", name: "North Americana", number: "359" },
  { slug: "grownfolkjamz", name: "Grown Folk JAMZ", number: "362" },
  { slug: "siriusxmsouthernrock", name: "SiriusXM Southern Rock", number: "504" },
  { slug: "the2pacchannel", name: "The 2Pac Channel", number: "508" },
  { slug: "usherradio", name: "Usher Radio", number: "509" },
  { slug: "milesdavisradio", name: "Miles Davis Radio", number: "510" },
  { slug: "poptop500", name: "Pop Top 500", number: "550" },
  { slug: "80son8top500", name: "80s on 8 Top 500", number: "551" },
  { slug: "90son9top500", name: "90s on 9 Top 500", number: "552" },
  { slug: "classicrocktop1000", name: "Classic Rock Top 1000", number: "553" },
  { slug: "hiphopchronicles", name: "Hip-Hop Chronicles", number: "556" },
  { slug: "countrytop1000", name: "Country Top 1000", number: "558" },
  { slug: "billboardtop500", name: "Billboard Top 500", number: "560" },
  { slug: "holidaytraditions", name: "Holiday Traditions", number: "602" },
  { slug: "disneyjrradio", name: "Disney Jr. Radio", number: "702" },
  { slug: "pandoranow", name: "Pandora Now", number: "703" },
  { slug: "soulcycleradio", name: "SoulCycle Radio", number: "704" },
  { slug: "siriusxmkpop", name: "SiriusXM K-Pop", number: "705" },
  { slug: "siriusxmlove", name: "SiriusXM Love", number: "708" },
  { slug: "siriusxo", name: "SiriusXO", number: "709" },
  { slug: "theloft", name: "The Loft", number: "710" },
  { slug: "pettysburiedtreasure", name: "Petty's Buried Treasure", number: "711" },
  { slug: "rockbar", name: "RockBar", number: "713" },
  { slug: "classicrockparty", name: "Classic Rock Party", number: "715" },
  { slug: "steviescoolestsongs", name: "Stevie's Coolest Songs", number: "721" },
  { slug: "soundcloudradio", name: "SoundCloud Radio", number: "724" },
  { slug: "steveaokisremixradio", name: "Steve Aoki's Remix Radio", number: "735" },
  { slug: "astateofarmin", name: "A State of Armin", number: "736" },
  { slug: "expertsonlyradio", name: "Experts Only Radio", number: "737" },
  { slug: "oneworldradio", name: "One World Radio", number: "738" },
  { slug: "saviorsundaydaily", name: "Savior Sunday Daily", number: "739" },
  { slug: "outsidersradio", name: "Outsiders Radio", number: "740" },
  { slug: "thevillage", name: "The Village", number: "741" },
  { slug: "metoperaradio", name: "Met Opera Radio", number: "744" },
  { slug: "siriusxmpops", name: "SiriusXM Pops", number: "745" },
  { slug: "spa", name: "Spa", number: "746" },
  { slug: "poplandia", name: "Poplandia", number: "754" },
  { slug: "thetragicallyhipradio", name: "The Tragically Hip Radio", number: "757" },
  { slug: "iceberg", name: "Iceberg", number: "758" },
  { slug: "lestubesfranco", name: "Les Tubes Franco", number: "759" },
  { slug: "chuchoscubabeyond", name: "Chucho's Cuba & Beyond", number: "760" },
  { slug: "celiacruzazucar", name: "Celia Cruz AZ\u00daCAR!", number: "761" },
  { slug: "caricia", name: "Caricia", number: "762" },
  { slug: "viva", name: "Viva", number: "763" },
  { slug: "latidos", name: "Latidos", number: "764" },
  { slug: "flownacion", name: "Flow Naci\u00f3n", number: "765" },
  { slug: "luna", name: "Luna", number: "766" },
  { slug: "rumbonmusic", name: "Rumb\u00f3n", number: "767" },
  { slug: "lakueva", name: "La Kueva", number: "768" },
  { slug: "siriusxmdhamaka", name: "SiriusXM Dhamaka", number: "769" },
]
